spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymapp
    username: gymusr
    password: Qwerty@123
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect